# Generated by Django 5.1.1 on 2024-11-30 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiarsBarMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the match started.')),
                ('end_date', models.DateTimeField(blank=True, help_text='Timestamp when the match ended.', null=True)),
                ('first_user', models.ForeignKey(help_text='Reference to the first user.', on_delete=django.db.models.deletion.CASCADE, related_name='liarsbar_matches_as_first_user', to=settings.AUTH_USER_MODEL)),
                ('fourth_user', models.ForeignKey(help_text='Reference to the fourth user.', on_delete=django.db.models.deletion.CASCADE, related_name='liarsbar_matches_as_fourth_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(help_text='Reference to the second user.', on_delete=django.db.models.deletion.CASCADE, related_name='liarsbar_matches_as_second_user', to=settings.AUTH_USER_MODEL)),
                ('third_user', models.ForeignKey(help_text='Reference to the third user.', on_delete=django.db.models.deletion.CASCADE, related_name='liarsbar_matches_as_third_user', to=settings.AUTH_USER_MODEL)),
                ('user_winner', models.ForeignKey(help_text='The user who won the match.', on_delete=django.db.models.deletion.CASCADE, related_name='liarsbar_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liars bar match',
            },
        ),
    ]
