# Generated by Django 5.1.1 on 2024-12-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liarsbar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='first_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the first user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liarsbar_matches_as_first_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='fourth_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the fourth user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liarsbar_matches_as_fourth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='second_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the second user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liarsbar_matches_as_second_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='third_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the third user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liarsbar_matches_as_third_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='user_winner',
            field=models.ForeignKey(blank=True, help_text='The user who won the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liarsbar_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
