# Generated by Django 5.1.1 on 2024-12-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liarsbar', '0002_alter_liarsbarmatch_first_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the match started.', null=True),
        ),
    ]
