# Generated by Django 5.1.1 on 2025-02-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liarsbar', '0003_alter_liarsbarmatch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liarsbarmatch',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the match ended.', null=True),
        ),
    ]
