# Generated by Django 5.1.1 on 2024-11-30 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_userimage_friendships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_stat', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('exp', models.IntegerField(default=0)),
                ('mmr', models.IntegerField(default=1000)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('longest_winstreak', models.IntegerField(default=0)),
                ('longest_losestreak', models.IntegerField(default=0)),
                ('total_points_scored', models.IntegerField(default=0)),
                ('longest_game', models.IntegerField(default=0)),
                ('time_on_site', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Stat',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_user_score', models.IntegerField(default=0, help_text='Score of the first user.')),
                ('second_user_score', models.IntegerField(default=0, help_text='Score of the second user.')),
                ('first_user_mmr_gain', models.IntegerField(default=0, help_text='MMR gain for the first user.')),
                ('second_user_mmr_gain', models.IntegerField(default=0, help_text='MMR gain for the second user.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the match started.')),
                ('end_date', models.DateTimeField(blank=True, help_text='Timestamp when the match ended.', null=True)),
                ('first_user', models.ForeignKey(help_text='Reference to the first user.', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(help_text='Reference to the second user.', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pong match',
            },
        ),
    ]
