# Generated by Django 5.1.1 on 2024-11-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
