# Generated by Django 5.1.1 on 2024-12-07 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_delete_userstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongmatch',
            name='first_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the first user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_first_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pongmatch',
            name='second_user',
            field=models.ForeignKey(blank=True, help_text='Reference to the second user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
