# Generated by Django 5.1.1 on 2025-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_pongmatch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongmatch',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the match ended.', null=True),
        ),
    ]
