# Generated by Django 5.1.1 on 2025-03-09 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_pongmatch_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, help_text='Timestamp when the tournament started.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Timestamp when the tournament ended.', null=True)),
                ('matches', models.ManyToManyField(help_text='Matches in the tournament.', related_name='tournaments', to='pong.pongmatch')),
                ('winner', models.ForeignKey(blank=True, help_text='The winner of the tournament.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pong tournament',
                'verbose_name_plural': 'Pong tournaments',
            },
        ),
    ]
