# Generated by Django 5.1.1 on 2025-03-09 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_pongtournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pongtournament',
            name='matches',
        ),
        migrations.AddField(
            model_name='pongtournament',
            name='players',
            field=models.ManyToManyField(help_text='User in the tournament.', related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
