# Generated by Django 5.1.1 on 2025-03-09 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_remove_pongtournament_matches_pongtournament_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongtournament',
            name='players',
            field=models.ManyToManyField(help_text='Users in the tournament.', related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
