global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gunicorn:8000']

rule_files:
  - "/tmp/alerting_rules.yml"
