# Generated by Django 5.1.1 on 2024-12-23 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0002_remove_chatmessage_chat_remove_chatmessage_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the chat was created.')),
                ('users', models.ManyToManyField(help_text='Users participating in this chat.', related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(help_text='The text of the message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the message was created.')),
                ('chat', models.ForeignKey(help_text='Reference to the chat.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.chat')),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
