# Generated by Django 5.1.1 on 2025-01-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20250104_0013'),
        ('website', '0017_alter_friendships_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='friendship',
            field=models.ForeignKey(help_text='Reference to the friendship.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.friendships'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
