# Generated by Django 5.1.1 on 2024-11-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_image', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_avatar', models.ImageField(default='media/default_avatar.png', upload_to='media/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Image',
                'verbose_name_plural': 'User Images',
            },
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'friends'), (3, 'block')], default=1, help_text='The user who initiated the friendship.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_user', models.ForeignKey(help_text='The user associated with the match history.', on_delete=django.db.models.deletion.CASCADE, related_name='riendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(help_text='The user who received the friendship request.', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Friendships',
                'indexes': [models.Index(fields=['status'], name='Friendships_status_5458f5_idx'), models.Index(fields=['first_user'], name='Friendships_first_u_c1b2b0_idx'), models.Index(fields=['second_user'], name='Friendships_second__86521c_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_user', 'second_user'), name='unique_friendships friendships')],
            },
        ),
    ]
