# Generated by Django 5.1.1 on 2024-11-30 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liarsbar', '0001_initial'),
        ('pong', '0001_initial'),
        ('website', '0002_userimage_friendships'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liarsbar_matches', models.ManyToManyField(blank=True, help_text='The Liars Bar matches associated with this user.', related_name='user_histories', to='liarsbar.liarsbarmatch')),
                ('pong_matches', models.ManyToManyField(blank=True, help_text='The Pong matches associated with this user.', related_name='user_histories', to='pong.pongmatch')),
                ('user', models.ForeignKey(help_text='The user associated with the match history.', on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match history',
            },
        ),
    ]
