# Generated by Django 5.1.1 on 2024-12-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='customUser',
            new_name='user',
        ),
    ]
