# Generated by Django 5.1.1 on 2024-12-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_customuser_userstats_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='User',
            new_name='user',
        ),
    ]
