# Generated by Django 5.1.1 on 2024-12-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_user_userimage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': 'user Image', 'verbose_name_plural': 'user Images'},
        ),
    ]
