# Generated by Django 5.1.1 on 2024-12-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_userimage_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendships',
            name='unique_friendships friendships',
        ),
    ]
