# Generated by Django 5.1.1 on 2024-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_friendships_unique_friendships_friendships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'friends'), (3, 'block'), (4, 'first_user_block'), (5, 'second_user_block')], default=1, help_text='The user who initiated the friendship.'),
        ),
    ]
