# Generated by Django 5.1.1 on 2024-12-13 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='first_user',
            field=models.ForeignKey(help_text='The user associated with the match history.', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friendships',
            unique_together={('first_user', 'second_user')},
        ),
    ]
