# Generated by Django 5.1.1 on 2024-12-13 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_friendships_first_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="User's unique username.", max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z0-9_.-]+$', 'Username can only contain letters, numbers, underscores, and periods.')]),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
