# Generated by Django 5.1.1 on 2024-12-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_userstats_exp_alter_userstats_longest_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'friends'), (3, 'block'), (6, 'blocked'), (4, 'first_user_block'), (5, 'second_user_block')], default=1, help_text='The user who initiated the friendship.'),
        ),
    ]
