# Generated by Django 5.1.1 on 2024-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'friends'), (3, 'first_user_block'), (4, 'second_user_block')], default=1, help_text='The user who initiated the friendship.'),
        ),
    ]
