# Generated by Django 5.1.1 on 2024-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.IntegerField(choices=[(1, 'first_user_pending'), (2, 'second_user_pending'), (3, 'friends'), (4, 'first_user_block'), (5, 'second_user_block')], help_text='The user who initiated the friendship.'),
        ),
    ]
