# Generated by Django 5.1.1 on 2025-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user_avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
