# Generated by Django 5.1.1 on 2025-02-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_userimage_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='longest_losestreak',
            new_name='current_winstreak',
        ),
    ]
