# Generated by Django 5.1.1 on 2025-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_longest_losestreak_userstats_current_winstreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='longest_game',
        ),
        migrations.AddField(
            model_name='userstats',
            name='longest_game_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
