# Generated by Django 5.1.1 on 2025-02-17 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_userstats_longest_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
