# Generated by Django 5.1.1 on 2025-02-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_userstats_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='time_on_site',
        ),
    ]
