# Generated by Django 5.1.1 on 2025-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_userstats_time_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='time_on_site',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
