# Generated by Django 5.1.1 on 2025-02-21 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_userstats_time_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='liarsbar_lose',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userstats',
            name='liarsbar_win',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
