# Generated by Django 5.1.1 on 2025-03-01 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_userstats_liarsbar_lose_userstats_liarsbar_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='time_on_site',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
