# Generated by Django 5.1.1 on 2025-03-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_userstats_time_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account42Nickname',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
