# Generated by Django 5.1.1 on 2025-03-10 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_user_account42nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='mmr',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
