# Generated by Django 5.1.1 on 2025-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_userstats_mmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='mmr',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
