services:
  postgres:
    build: postgres/
    image: postgres
    container_name: postgres
    user: "13449:4222"
    env_file: postgres/env/.env.prod.db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: 
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ft_transcendence -U 42user"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    build: redis/
    image: redis
    container_name: redis
    user: "13449:4222"
    restart: always
    networks: 
      - backend
  gunicorn:
    build: site/
    image: gunicorn
    container_name: gunicorn
    user: "13449:4222"
    env_file: site/env/.env.backend
    restart: always
    networks: 
      - backend
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/media
    depends_on:
      - postgres
      - redis
  nginx:
    container_name: nginx
    image: nginx
    build: nginx/
    user: "13449:4222"
    ports:
      - 8080:8080
    restart: always
    expose:
      - 80
    networks: 
      - backend
    depends_on: 
      - gunicorn
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/media
  daphne:
    image: daphne
    build:
      context: ./
      dockerfile: daphne/Dockerfile
    container_name: daphne
    user: "13449:4222"
    env_file: site/env/.env.backend
    restart: always
    networks: 
      - backend
    depends_on: 
      - gunicorn

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: /home/evocatur/goinfree/data/pg_data
      o: bind
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/evocatur/goinfree/data/static_volume
      o: bind
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/evocatur/goinfree/data/media_volume
      o: bind

networks:
  backend:
    driver: bridge
