services:
  ft_transcendence-postgres:
    container_name: db
    env_file:
      - path: database/env/.env.prod.db
    image: postgres:15
    volumes:
    - pg_data:/var/lib/postgresql/data
    restart: always
  nginx:
    container_name: nginx
    build: nginx/
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/mediafiles
    ports:
      - 1337:443
    depends_on:
      - ft_transcendence-site
    restart: always
  redis:
    image: redis:7
    expose:
      - 6379
  ft_transcendence-site:
    container_name: ft_transcendence-site
    build:
      context: site/
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/mediafiles
    expose:
      - 8000
    env_file:
      - path: site/env/.env.backend
    depends_on:
      - ft_transcendence-postgres
      - redis
    restart: always

volumes:
  pg_data:
  static_volume:
  media_volume: