services:
  ft_transcendence-postgres:
    build: database/
    container_name: db
    env_file:
      - path: database/env/.env.prod.db
    volumes:
    - pg_data:/var/lib/postgresql/data
    restart: always
  nginx:
    build: nginx/
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/mediafiles
    ports:
      - 1337:80
    depends_on:
      - ft_transcendence-site
    restart: always
  ft_transcendence-site:
    build: 
      context: site/
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/ft_transcendence/staticfiles
      - media_volume:/home/app/ft_transcendence/mediafiles
    container_name: django
    expose:
      - 8000
    env_file:
      - path: site/env/.env.backend
    depends_on:
      - ft_transcendence-postgres
    restart: always

volumes:
  pg_data:
  static_volume:
  media_volume: